# Generated by Django 5.1.1 on 2024-10-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv_service', '0002_alter_table_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_confirm',
            field=models.BooleanField(default=False, verbose_name='Поле подтверждения бронирования'),
        ),
    ]
